import React from 'react';
import { BrowserRouter, useRoutes } from 'react-router-dom';
import routes from './Routes';

const AppRoutes = () => {
  const element = useRoutes(routes);
  return element;
};

//TODO: COMPROBAR QUE TODO SEA REACT.FC
//TODO: COMPROBAR QUE SE USAN LAS CONSTANTES DE API-URLS
//TODO: COMPROBAR QUE SE USAN LAS COSNTANTES DE PATHS
//TODO: SEPARAR TODOS LOS IMPORTS DE ARCHIVOS INTERNOS Y LIBRERIAS EXTERNAS
//TODO: CAMBIAR LO DE STARS EN USERINFO Y DEMÁS
//TODO: BUSCAR CUALQUIER PARTE DEL CODIGO DONDE SE DECLARE EL TIPO DE USUARIO COMO STRING Y LIMITAR
//      EL TIPO DE USUARIO A EL TIPO ROLES DEFINIDO EN CONSTANTS, UN EJEMPLO EN USERSERVICE DEL ADMINPANEL.
//TODO: EN LAS LLAMADAS A LA API CAMBIAR APIRESPONSE POR "DATA"
//TODO: BUSCAR Y ELIMINAR LA PALABRA CLAVE STARS O STAR EN TODO EL CODIGO
//TODO: COMPROBAR QUE CADA CARPETA EN PAGES TENGA SU CARPETA STYLES SI LO NECESITA
//TODO: REVISAR LOS HOOKS DE USO DE FUNCIONES DE LA API PARA ASEGURAR QUE ESTÉN ESTANDARIZADOS
//TODO: REPASAR EL INDEX.CSS PARA VER SI SE PUEDE QUITAR ALGO O MOVERLO A LA CARPETA STYLES DE LOS COMPONENTES
//TODO: EN EL ARHCIVO DE ROUTES.TSX, SE ESTÁN PASANDO DIRECTAMENTE URLS A ROLE SERVICE, SOLUCIONARLO
//      HACER QUE SE PASEN TAMBIEN COMO CONSTNATE Y NO COMO TEXTO TAL CUAL.
const App: React.FC = () => {
  return (
    <BrowserRouter>
      <AppRoutes />
    </BrowserRouter>
  );
};

export default App;
