import React from 'react';
import { BrowserRouter, useRoutes } from 'react-router-dom';
import { AuthProvider } from '../context/AuthContext';
import { ThemeProvider } from '../context/ThemeContext';
import routes from './Routes';

const AppRoutes = () => {
  const element = useRoutes(routes);
  return element;
};

//TODO: ORGANIZACION CSS:
/**
 * 
 *  .button {
  /* Posicionamiento */
/*   display: inline-block;
  margin: 10px;
  padding: 8px 16px; */

/* Estilos visuales */
/*   background-color: #007bff;
  color: white;
  border-radius: 5px; */

/* Tipografía */
/*  font-size: 16px;
  font-weight: bold; */

/* Otros */
/*   transition: background-color 0.3s ease;
} */

//TODO: mIRAR SI SE PUEDE CAMBIAR COMO SE USAN LAS APIS, EN VEZ DE IMPORTAR LOS METODOS DEFINIDOS EN USER.TS POR EJEMPLO.
//      IMPORTAR DE OTRA MANERA DEL ESTILO A IMPORT USER Y HACER DESPUES USERAPI.GET USERAPI.DELETE... y ESE TIPO DE COSAS.

//TODO: Poner mensajes de required en los formularios.
//TODO: CAMBIAR COÓMO SE ORGANIZAN LA NAVBAR Y EL CONTENDIO EN TODAS LAS PAGINAS PRINCIPALES
//      ACTUALMENTE SE ESTÁN SEPARANDO POR VH Y NO POR PORCENTAJES, CAMBIAR ESO EJEMPLO: ADMINPANEL
//TODO: iNTENBTAR CAMBIAR TODOS LOS MARGENES Y COSAS QUE SEA NECESARIO Y QUE ESTENE EN PX POR VH
//TODO: ORGANIZAR LOS CSS SEPARANDO LOS ITEMS DE LAS CLASES CSS, COLORES, BORDES..
//TODO: CON EL BUSCADOR, BUSCAR BORDER-RADIUS PARA ASEGURARTE DE QUE LOS BORDES SON IGUALES PARA TODOS LOS COMPONTES 15PX EN PRINCIPIO
//TODO: REVISAR QUE TODOS LOS ARCHIVOS ESTÉN DOCUMENTADOS CON JSDOC
//TODO: CAMBIAR TODO DONDE PONGA USERTYPE POR ROLE O USER ROLE
//TODO: COMPROBAR QUE SE USAN LAS CONSTANTES DE API-URLS
//TODO: COMPROBAR QUE SE USAN LAS COSNTANTES DE PATHS
//TODO: SEPARAR TODOS LOS IMPORTS DE ARCHIVOS INTERNOS Y LIBRERIAS EXTERNAS
//TODO: CAMBIAR LO DE STARS EN USERINFO Y DEMÁS
//TODO: BUSCAR CUALQUIER PARTE DEL CODIGO DONDE SE DECLARE EL TIPO DE USUARIO COMO STRING Y LIMITAR
//      EL TIPO DE USUARIO A EL TIPO ROLES DEFINIDO EN CONSTANTS, UN EJEMPLO EN USERSERVICE DEL ADMINPANEL.
//TODO: EN LAS LLAMADAS A LA API CAMBIAR APIRESPONSE POR "DATA"
//TODO: BUSCAR Y ELIMINAR LA PALABRA CLAVE STARS O STAR EN TODO EL CODIGO
//TODO: COMPROBAR QUE CADA CARPETA EN PAGES TENGA SU CARPETA STYLES SI LO NECESITA
//TODO: REVISAR LOS HOOKS DE USO DE FUNCIONES DE LA API PARA ASEGURAR QUE ESTÉN ESTANDARIZADOS
//TODO: REPASAR EL INDEX.CSS PARA VER SI SE PUEDE QUITAR ALGO O MOVERLO A LA CARPETA STYLES DE LOS COMPONENTES
//TODO: EN EL ARHCIVO DE ROUTES.TSX, SE ESTÁN PASANDO DIRECTAMENTE URLS A ROLE SERVICE, SOLUCIONARLO
//      HACER QUE SE PASEN TAMBIEN COMO CONSTNATE Y NO COMO TEXTO TAL CUAL.
//TODO: bUSCAR LA PALABRA WORLD EN EL CODIGO Y SUSTITUIR POR SUBJECT
//TODO: ASEGURARSE QUE NO SE ESTÁ USANDO TYPE EN NINGUN LADO Y SE ESTÁ USANDO INTERFACE EN SU LUGAR
//TODO: CAMBIAR LOS NOMBRES DE LOS ARCHIVOS DE SERVICIOS API EN TODA LA PARTE DE ADMINPANEL
//TODO: EN LA PARTE DE ADMIN PANEL TAMBIEN SE ESTÁ REPITIENDO EL CODIGO DE LOS SERVICIOS API DE SUBJECT Y GAME
//TODO: COMPROBAR QUE NO HAYA NADA EN ESPAÑOL EN EL CODIGO
//TODO: HACER UN COMPONENTE BASE PARA LOS MENSAJES DE ERROR Y PROBARLO EN TODAS LAS PAGINAS.
//      FALLO DE LOGIN -> CREDENCIALES INCORRECTAS
//      FALLO DE LOGIN -> SERVER ERROR
//      FALLO DE CARGA ASIGNATURAS -> SERVER ERROR
//      FALLO DE CARGA DE JUEGOS -> SERVER ERROR
//      FALLO DE CARGA...
//TODO: GRAN PREGUNTA: CUANDO SE CONSULTA EL RANKING POR JUEGOS, SE MUESTRAN TODOS LOS JUEGOS QUE EXISTEN? O SE FILTRA POR ASIGNATURA O ALGO
const App: React.FC = () => {
  return (
    <BrowserRouter>
      <AuthProvider>
        <ThemeProvider>
          <AppRoutes />
        </ThemeProvider>
      </AuthProvider>
    </BrowserRouter>
  );
};

export default App;
