import { useEffect, useState } from 'react';

import { Subject, SubjectApi } from '../../../api/subject';

const useSubject = () => {
  const [subjects, setSubjects] = useState<Subject[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadSubjects = async () => {
      try {
        const data = await SubjectApi.getAll();

        /*  const data = [
          {
            id: 1,
            name: 'Matemáticas',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-math.jpg',
            position: 1,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 2,
            name: 'Lengua',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-language.jpg',
            position: 2,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 3,
            name: 'Historia',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-history.jpg',
            position: 3,
            isOpen: false,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 4,
            name: 'Ciencias',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-science.jpg',
            position: 4,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 5,
            name: 'Inglés',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-english.jpg',
            position: 5,
            isOpen: false,
            isVisible: true,
          },
          {
            id: 5,
            name: 'Inglés',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-english.jpg',
            position: 5,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 5,
            name: 'Inglés',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-english.jpg',
            position: 5,
            isOpen: false,
            isVisible: true,
          },
          {
            id: 5,
            name: 'Inglés',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-english.jpg',
            position: 5,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 5,
            name: 'Inglés',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-english.jpg',
            position: 5,
            isOpen: true,
            isVisible: true,
          },
          {
            id: 5,
            name: 'Inglés',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-english.jpg',
            position: 5,
            isOpen: false,
            isVisible: true,
          },
          {
            id: 5,
            name: 'Inglés',
            img: '',
            imgBackground: 'https://example.com/imgs/bg-english.jpg',
            position: 5,
            isOpen: true,
            isVisible: true,
          },
        ]; */
        setSubjects(data);
      } catch (error: unknown) {
        if (error instanceof Error) {
          setError(error.message);
        } else {
          setError('An unknown error occurred');
        }
      }
    };

    loadSubjects();
  }, []);

  return { subjects, error };
};

export default useSubject;
